# 한글 입출력 설정
#server:
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true


# port 설정
server:
  port: 9999

spring:

  # h2 database
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/onedayboot
    driverClassName: org.h2.Driver
    username: sa
    password: 1234

 # jpa 연동
  jpa:
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true # 주석 표시(쿼리문 출력시)

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace
            SQL: DEBUG

